[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datetime = "0.5.2"
distro-rs = { path = "../../../framework/distro-rs" }
uuid = "0.8.2"
